language: node_js
node_js:
  - 'stable'
addons:
  postgresql: "9.3"

#services:
#  - postgresql

env:
- JAMRUN=test

before_script:
  - psql --version
  - psql -c 'create database jamstest;' -U postgres