language: node_js
node_js:
  - 'stable'
services:
  - postgresql
before_script:
  - psql -c 'create database jamstest;' -U postgres
  - cp server/config/config.example.js server/config/config.js
  - cp server/config/aws.example.js server/config/aws.json