version: '2'

services:

  db:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: '----------'
      POSTGRES_PASSWORD: '------------'
      POSTGRES_DB: '--------'

  compression:
    build: ./compression_server
    # image: compression
    environment:
      PORT: 4000
    ports:
      - "4000:4000"
  
  primary:
    build: .
    volumes:
      - .
    links:
      - db
      - compression
    ports:
      - "3000:3000"
    environment:
      SEQ_DB: '----------'
      SEQ_USER: '----------'
      SEQ_PW: '---------'
      PORT: 3000
      DATABASE_URL: ---------------------
      COMPRESSION_SERVER: 'http://compression:4000'